version: '3.8'
services:
  front:
    container_name: front
    build:
      context: ../projects/frontend
      dockerfile: ./Dockerfile.frontend
    volumes:
      - ../projects/frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:8080'
    environment:
      NODE_ENV: development
    depends_on:
      - node_app

  node_app:
    container_name: node_app
    build:
      context: ../projects/backend
      dockerfile: ./Dockerfile.backend
    image: francescoxx/node_live_app
    ports:
      - '3000:3001'
    environment:
      - PG_DB=node_live_db
      - PG_USER=francesco
      - PG_PASSWORD=12345
      - PG_HOST=node_db
    depends_on:
      - node_db

  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=node_live_db
      - POSTGRES_USER=francesco
      - POSTGRES_PASSWORD=12345
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
