FROM node:alpine AS build
ENV NODE_ENV=development
WORKDIR /app
COPY package.json ./
RUN yarn install
RUN yarn global add next

FROM node:alpine
ENV NODE_ENV=development
WORKDIR /app
COPY . .
COPY --from=build /app/node_modules ./node_modules/
CMD yarn dev
